### ISSUE TITLE
geri.dev

### ISSUE THREAD

**Issue by Geri-Borbas** [NotGeri/NotGeri#1]
Hi,
I want to make an offer for geri.dev domain. 💎
Is there any contact where we can talk? (the admin email seems unresponsive)
Could you perhaps redirect me to the registar of the domain?

**Comment by NotGeri** [comment]
Hello, 👋

No, even though the site itself is fairly dead, `geri.dev` is a base domain for almost all my previous and current side projects. 

Unless you can get `geri.hu` (Hungarian TLD) or any of the official ones such as `geri.net`, `geri.com`, or `geri.org` in return, I will not be able to sell this any time soon.

I have attempted to contact `geri.hu` and `geri.com` numerous times with no luck or response, however.

**Comment by Geri-Borbas** [comment]
Hey there, thanks for getting back!
I still have my very own portfolio (from 2008) at geri.hu, so I guess there is hope we can work something out (?).
Ok, I'll try to get to geri.hu first.

**Comment by Geri-Borbas** [comment]
💡 _UPDATE: Wow, just discovered you contacted me years ago to buy geri.hu (2020.12.08)._

**Comment by NotGeri** [comment]
Hah, that indeed is possible. Let me send an email and see what we can figure out. 👍

**Comment by Geri-Borbas** [comment]
Hello there, I managed to acquire `geri.hu` since then, I'm the registered owner now.
Could we resume negotiations on `geri.dev`?

On the admin email of course, sorry to keep nudging you here, yet you seem more responsive on GitHub. 😂

**Comment by Geri-Borbas** [comment]
🥺

**Comment by Geri-Borbas** [comment]
Hi, could you please confirm, that you are **not selling `geri.dev`**?
I'm planning to start to look for other `dev` domains, yet I wanted to double-check one last time. 😔

> I saw that you put the content on hold, so I thought it is worth reaching out again.
